### ISSUE TITLE
Cant download another Video

### ISSUE THREAD

**Issue by HusseinMahmood** [AnyDownloader/YouTubeDownloader#2]
it work in your video only
im trying another videos in youtube and i cant download it 
show to me Error 403
![image](https://user-images.githubusercontent.com/75856096/129490559-0800b241-a583-4645-b6d8-b9ecd6b3391d.png)

try this url : https://www.youtube.com/watch?v=5gWaWSSioUA

**Comment by intracomof** [comment]
Fixed
